services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "main"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./.env:/app/.env:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - bot-network
    stop_grace_period: 30s

networks:
  bot-network:
    driver: bridge